/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as friendTechSol from "./FriendTech.sol";
export type { friendTechSol };
import type * as interfaces from "./interfaces";
export type { interfaces };
export type { FriendWrap } from "./FriendWrap";
