/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { FriendtechSharesV1__factory } from "./FriendtechSharesV1__factory";
export { Ownable__factory } from "./Ownable__factory";
