/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as friendTechSol from "./FriendTech.sol";
export * as interfaces from "./interfaces";
export { FriendWrap__factory } from "./FriendWrap__factory";
