/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IFriendTechV1,
  IFriendTechV1Interface,
} from "../../../contracts/interfaces/IFriendTechV1";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "sharesSubject",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "buyShares",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "sharesSubject",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "sellShares",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
];

export class IFriendTechV1__factory {
  static readonly abi = _abi;
  static createInterface(): IFriendTechV1Interface {
    return new utils.Interface(_abi) as IFriendTechV1Interface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IFriendTechV1 {
    return new Contract(address, _abi, signerOrProvider) as IFriendTechV1;
  }
}
